version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # 외부 포트 80을 컨테이너의 80번 포트로 매핑
      - "443:443"  # HTTPS 연결용 ㅅㅏ실 지금은 필요없음
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 마운트
    depends_on:
      - webapp
      - springboot
  webapp:
    image: sungwoo166/react-app:latest  # 리액트 앱 이미지
    container_name: react-web-app
    expose:
      - "3000"  # 컨테이너 내부에서 사용할 포트
  springboot:
    image: sungwoo166/jenkins:latest  # Jenkins 이미지
    container_name: springboot-web-service
    ports:
      - "8080:8080"  # Jenkins 웹 인터페이스 접근 포트
